name: Clojure CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: 📦 Get LFTP
      run: sudo apt install lftp
    - name: Install dependencies
      run: lein deps
    - name: Build notebook
      run: lein run
    - name: check
      run: ls
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        folder: public/build
