name: Clojure CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: check
      run: ls
    - name: Install dependencies
      run: lein deps
    - name: Build notebook
      run: lein run
    - name: check
      run: ls
    - name: 🚀 Deploy
      uses: JamesIves/github-pages-deploy-action@4
      with:
        branch: gh-pages
        folder: public/build
