name: Clojure CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: 📦 Get LFTP
      run: sudo apt install lftp
    - name: Install dependencies
      run: lein deps
    - name: Build notebook
      run: lein run
    - name: 🛠️ Configure LFTP
      run: |
        mkdir ~/.lftp
        echo "set ssl:ca-file ~/.lftp/certs.crt;set ssl:check-hostname no;" >> ~/.lftp/rc
        echo "${{ secrets.FTP_CERTS_BASE64 }}" | base64 --decode > ~/.lftp/certs.crt
    - name: Deploy to webpage
      run: lftp sftp://${{ secrets.FTP_PATH }} --user ${{ secrets.FTP_USER }} --password ${{ secrets.FTP_PASS }} -e "set ftp:ssl-allow no; mirror -R public/build ${{ secrets.FTP_FOLDER }} --only-newer; quit"
